# Generated by Django 4.2.12 on 2024-05-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_course', models.CharField(max_length=100, null=True)),
                ('user_industry', models.CharField(max_length=100, null=True)),
                ('user_skills', models.CharField(max_length=100, null=True)),
                ('user_interest', models.CharField(max_length=100, null=True)),
                ('career_one', models.CharField(max_length=100, null=True)),
                ('career_two', models.CharField(max_length=100, null=True)),
                ('career_three', models.CharField(max_length=100, null=True)),
                ('career_one_prob', models.IntegerField(null=True)),
                ('career_two_prob', models.IntegerField(null=True)),
                ('career_three_prob', models.IntegerField(null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recomee__app.username')),
            ],
        ),
    ]
