# Generated by Django 4.2.12 on 2024-05-29 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomee__app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputresults',
            name='user_name',
        ),
        migrations.AddField(
            model_name='inputresults',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
