# Generated by Django 4.2.12 on 2024-05-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomee__app', '0002_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputresults',
            name='user_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recomee__app.username'),
        ),
    ]
