# Generated by Django 4.2.12 on 2024-05-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomee__app', '0007_remove_inputresults_user_name_inputresults_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputresults',
            name='user_name',
        ),
        migrations.AddField(
            model_name='username',
            name='input_and_results',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recomee__app.inputresults'),
        ),
    ]
