# Generated by Django 4.2.12 on 2024-05-21 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recomee__app', '0009_remove_username_input_and_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputresults',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
