# Generated by Django 4.2.12 on 2024-05-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomee__app', '0010_alter_inputresults_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputresults',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
