# Generated by Django 4.2.12 on 2024-05-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomee__app', '0011_alter_inputresults_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='id',
        ),
        migrations.AddField(
            model_name='username',
            name='unique_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
